version: '3.4'

services:
  ecommerce.api.customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"

  ecommerce.api.orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"


  ecommerce.api.products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

    ports:
      - "80/http"


  ecommerce.api.search:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Products=http://ecommerce.api.products
      - Services__Customers=http://ecommerce.api.customers
      - Services__Orders=http://ecommerce.api.orders
    ports:
      - "80/http"

